[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
cassie = "377f8fpEExurtJNPfjNF7sTLEL9ZLCnCC4FCwDxU6BFz"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"
